# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.srcs/sources_1/bd/top_block/ip/top_block_util_ds_buf_7_0/top_block_util_ds_buf_7_0.xci
# IP: The module: 'top_block_util_ds_buf_7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_util_ds_buf_7_0/top_block_util_ds_buf_7_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_block_util_ds_buf_7_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_util_ds_buf_7_0/top_block_util_ds_buf_7_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_block_util_ds_buf_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.srcs/sources_1/bd/top_block/ip/top_block_util_ds_buf_7_0/top_block_util_ds_buf_7_0.xci
# IP: The module: 'top_block_util_ds_buf_7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_util_ds_buf_7_0/top_block_util_ds_buf_7_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_block_util_ds_buf_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_util_ds_buf_7_0/top_block_util_ds_buf_7_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_block_util_ds_buf_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
