# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/GTH.xdc

# XDC: new/main_io.xdc

# XDC: new/samidare_io.xdc

# XDC: new/Pblock.xdc

# XDC: new/Timing.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_300M1_0/top_block_rst_clk_wiz_0_300M1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_300M1_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_300M1_0} -quiet] -quiet

# IP: ip/gig_ethernet_pcs_pma_0_gt/gig_ethernet_pcs_pma_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] -quiet

# Block Designs: bd/top_block/top_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block || ORIG_REF_NAME==top_block} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_2/top_block_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_2 || ORIG_REF_NAME==top_block_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_2/top_block_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_2 || ORIG_REF_NAME==top_block_xlconstant_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_LED_REG_READ_SEPARAT_0_0/top_block_LED_REG_READ_SEPARAT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_LED_REG_READ_SEPARAT_0_0 || ORIG_REF_NAME==top_block_LED_REG_READ_SEPARAT_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_LED_REG_READ_SEPARAT_1_0/top_block_LED_REG_READ_SEPARAT_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_LED_REG_READ_SEPARAT_1_0 || ORIG_REF_NAME==top_block_LED_REG_READ_SEPARAT_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_u_led_inst_0_0/top_block_u_led_inst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_u_led_inst_0_0 || ORIG_REF_NAME==top_block_u_led_inst_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_vio_0_0/top_block_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_vio_0_0 || ORIG_REF_NAME==top_block_vio_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_0_125M_0/top_block_rst_clk_wiz_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_cdc_gen_0_0/top_block_xpm_cdc_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_cdc_gen_0_0 || ORIG_REF_NAME==top_block_xpm_cdc_gen_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_1_320M_0/top_block_rst_clk_wiz_1_320M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_1_320M_1/top_block_rst_clk_wiz_1_320M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_1 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_cdc_gen_0_2/top_block_xpm_cdc_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_cdc_gen_0_2 || ORIG_REF_NAME==top_block_xpm_cdc_gen_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_cdc_gen_0_3/top_block_xpm_cdc_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_cdc_gen_0_3 || ORIG_REF_NAME==top_block_xpm_cdc_gen_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_0_125M_1/top_block_rst_clk_wiz_0_125M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_1 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_0_300M1_0/top_block_rst_clk_wiz_0_300M1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_300M1_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_300M1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_cdc_gen_2_0/top_block_xpm_cdc_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_cdc_gen_2_0 || ORIG_REF_NAME==top_block_xpm_cdc_gen_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_bram_ctrl_0_0/top_block_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_bram_ctrl_0_0 || ORIG_REF_NAME==top_block_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_blk_mem_gen_0_0/top_block_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_blk_mem_gen_0_0 || ORIG_REF_NAME==top_block_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_bram_ctrl_1_0/top_block_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_bram_ctrl_1_0 || ORIG_REF_NAME==top_block_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_iic_0_0/top_block_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_iic_0_0 || ORIG_REF_NAME==top_block_axi_iic_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_iobuf_vhdl_0_0/top_block_iobuf_vhdl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_iobuf_vhdl_0_0 || ORIG_REF_NAME==top_block_iobuf_vhdl_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_iobuf_vhdl_1_0/top_block_iobuf_vhdl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_iobuf_vhdl_1_0 || ORIG_REF_NAME==top_block_iobuf_vhdl_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_I2C_Controller_v1_0_0_1/top_block_I2C_Controller_v1_0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_I2C_Controller_v1_0_0_1 || ORIG_REF_NAME==top_block_I2C_Controller_v1_0_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_init_i2c_v1_0_0_0/top_block_init_i2c_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_init_i2c_v1_0_0_0 || ORIG_REF_NAME==top_block_init_i2c_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_3/top_block_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_3 || ORIG_REF_NAME==top_block_xlconstant_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_1_4/top_block_xlconcat_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_1_4 || ORIG_REF_NAME==top_block_xlconcat_1_4} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_2_2/top_block_xlconcat_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_2_2 || ORIG_REF_NAME==top_block_xlconcat_2_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_1_3/top_block_xlconcat_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_1_3 || ORIG_REF_NAME==top_block_xlconcat_1_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_1_0/top_block_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_1_0 || ORIG_REF_NAME==top_block_xlconcat_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_appunit_fifo_out_0_0/top_block_cs_appunit_fifo_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_appunit_fifo_out_0_0 || ORIG_REF_NAME==top_block_cs_appunit_fifo_out_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_c_counter_binary_0_0/top_block_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_c_counter_binary_0_0 || ORIG_REF_NAME==top_block_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_4/top_block_util_vector_logic_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_4 || ORIG_REF_NAME==top_block_util_vector_logic_1_4} -quiet] -quiet

# IP: bd/top_block/ip/top_block_fifo_generator_0_0_2/top_block_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_0_0 || ORIG_REF_NAME==top_block_fifo_generator_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_fifo_generator_0_1/top_block_fifo_generator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_0_1 || ORIG_REF_NAME==top_block_fifo_generator_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_fifo_generator_1_0_2/top_block_fifo_generator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_1_0 || ORIG_REF_NAME==top_block_fifo_generator_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_fifo_generator_2_0_2/top_block_fifo_generator_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_2_0 || ORIG_REF_NAME==top_block_fifo_generator_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_data_sender_v1_0_0_0/top_block_data_sender_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_data_sender_v1_0_0_0 || ORIG_REF_NAME==top_block_data_sender_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axis_data_fifo_0_0/top_block_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axis_data_fifo_0_0 || ORIG_REF_NAME==top_block_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_fifo_slicer_0_0/top_block_cs_fifo_slicer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_fifo_slicer_0_0 || ORIG_REF_NAME==top_block_cs_fifo_slicer_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_appunit_merge_0_0/top_block_cs_appunit_merge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_appunit_merge_0_0 || ORIG_REF_NAME==top_block_cs_appunit_merge_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_trigger_manager_0_0/top_block_trigger_manager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_trigger_manager_0_0 || ORIG_REF_NAME==top_block_trigger_manager_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_reduced_logic_0_0/top_block_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_reduced_logic_0_0 || ORIG_REF_NAME==top_block_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_0_0/top_block_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_0_0 || ORIG_REF_NAME==top_block_xlconcat_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_event_builder_0_0/top_block_cs_event_builder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_event_builder_0_0 || ORIG_REF_NAME==top_block_cs_event_builder_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_data_processor_0_0/top_block_cs_data_processor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_data_processor_0_0 || ORIG_REF_NAME==top_block_cs_data_processor_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_das_rx_0_0/top_block_cs_das_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_das_rx_0_0 || ORIG_REF_NAME==top_block_cs_das_rx_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_threshold_comparator_0_0/top_block_threshold_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_threshold_comparator_0_0 || ORIG_REF_NAME==top_block_threshold_comparator_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_mii_initializer_0_0/top_block_mii_initializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_mii_initializer_0_0 || ORIG_REF_NAME==top_block_mii_initializer_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_0/top_block_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_0 || ORIG_REF_NAME==top_block_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_0/top_block_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_0 || ORIG_REF_NAME==top_block_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_2_0/top_block_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_2_0 || ORIG_REF_NAME==top_block_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_1/top_block_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_1 || ORIG_REF_NAME==top_block_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_1/top_block_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_1 || ORIG_REF_NAME==top_block_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_2/top_block_util_vector_logic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_2 || ORIG_REF_NAME==top_block_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_2_1/top_block_util_vector_logic_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_2_1 || ORIG_REF_NAME==top_block_util_vector_logic_2_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_3_0/top_block_util_vector_logic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_3_0 || ORIG_REF_NAME==top_block_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_0/top_block_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_0 || ORIG_REF_NAME==top_block_xlconstant_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_1/top_block_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_1 || ORIG_REF_NAME==top_block_xlconstant_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_1_2/top_block_xlconstant_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_1_2 || ORIG_REF_NAME==top_block_xlconstant_1_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_1_3/top_block_xlconstant_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_1_3 || ORIG_REF_NAME==top_block_xlconstant_1_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_RESET_INST_0_0/top_block_RESET_INST_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_RESET_INST_0_0 || ORIG_REF_NAME==top_block_RESET_INST_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_gig_ethernet_pcs_pma_0_0/top_block_gig_ethernet_pcs_pma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==top_block_gig_ethernet_pcs_pma_0_0} -quiet] -quiet

# IP: ip/gig_ethernet_pcs_pma_0_2/gig_ethernet_pcs_pma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet

# IP: ip/gig_ethernet_pcs_pma_0_gt/gig_ethernet_pcs_pma_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] -quiet

# IP: bd/top_block/ip/top_block_reg_switch_0_0/top_block_reg_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_reg_switch_0_0 || ORIG_REF_NAME==top_block_reg_switch_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_fakernet_top_0_0/top_block_fakernet_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_fakernet_top_0_0 || ORIG_REF_NAME==top_block_fakernet_top_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_native_to_axi_lite_v_0_0/top_block_native_to_axi_lite_v_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_native_to_axi_lite_v_0_0 || ORIG_REF_NAME==top_block_native_to_axi_lite_v_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_data_receiver_v1_0_0_0/top_block_data_receiver_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_data_receiver_v1_0_0_0 || ORIG_REF_NAME==top_block_data_receiver_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_1_0 || ORIG_REF_NAME==top_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_0 || ORIG_REF_NAME==top_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_delay_adjust_init_v1_0_0/top_block_delay_adjust_init_v1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_delay_adjust_init_v1_0_0 || ORIG_REF_NAME==top_block_delay_adjust_init_v1_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_idelay_top_v2_0_0/top_block_idelay_top_v2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_idelay_top_v2_0_0 || ORIG_REF_NAME==top_block_idelay_top_v2_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_SAMPA_TRG_EN_v1_0_0_0/top_block_SAMPA_TRG_EN_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_SAMPA_TRG_EN_v1_0_0_0 || ORIG_REF_NAME==top_block_SAMPA_TRG_EN_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_OBUFDS_TRG_0_0/top_block_OBUFDS_TRG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_OBUFDS_TRG_0_0 || ORIG_REF_NAME==top_block_OBUFDS_TRG_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_TRG_MODULE_0_0/top_block_TRG_MODULE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_TRG_MODULE_0_0 || ORIG_REF_NAME==top_block_TRG_MODULE_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xbar_1/top_block_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xbar_1 || ORIG_REF_NAME==top_block_xbar_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_mem_intercon_3/top_block_axi_mem_intercon_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_mem_intercon_3 || ORIG_REF_NAME==top_block_axi_mem_intercon_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_OBUFDS_CLKSOIN_0_0/top_block_OBUFDS_CLKSOIN_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_OBUFDS_CLKSOIN_0_0 || ORIG_REF_NAME==top_block_OBUFDS_CLKSOIN_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_3/top_block_util_vector_logic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_3 || ORIG_REF_NAME==top_block_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_bits_to_n_samples_0_0/top_block_bits_to_n_samples_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_bits_to_n_samples_0_0 || ORIG_REF_NAME==top_block_bits_to_n_samples_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_1_4/top_block_xlconstant_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_1_4 || ORIG_REF_NAME==top_block_xlconstant_1_4} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_2_1/top_block_xlconcat_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_2_1 || ORIG_REF_NAME==top_block_xlconcat_2_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_3/top_block_util_vector_logic_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_3 || ORIG_REF_NAME==top_block_util_vector_logic_1_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_OBUFDS_TRG_0_1/top_block_OBUFDS_TRG_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_OBUFDS_TRG_0_1 || ORIG_REF_NAME==top_block_OBUFDS_TRG_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_OBUFDS_CONST_0_1/top_block_OBUFDS_CONST_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_OBUFDS_CONST_0_1 || ORIG_REF_NAME==top_block_OBUFDS_CONST_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_OBUFDS_CONST_0_0/top_block_OBUFDS_CONST_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_OBUFDS_CONST_0_0 || ORIG_REF_NAME==top_block_OBUFDS_CONST_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_SAMPA_PON_v1_0_0_0/top_block_SAMPA_PON_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_SAMPA_PON_v1_0_0_0 || ORIG_REF_NAME==top_block_SAMPA_PON_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_GPIO_rx_0_0/top_block_GPIO_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_GPIO_rx_0_0 || ORIG_REF_NAME==top_block_GPIO_rx_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_0/top_block_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_0 || ORIG_REF_NAME==top_block_xlslice_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_c_counter_binary_0_1/top_block_c_counter_binary_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_c_counter_binary_0_1 || ORIG_REF_NAME==top_block_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_ccd_dflop_0_0/top_block_cs_ccd_dflop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_ccd_dflop_0_0 || ORIG_REF_NAME==top_block_cs_ccd_dflop_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_ccd_dflop_0_2/top_block_cs_ccd_dflop_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_ccd_dflop_0_2 || ORIG_REF_NAME==top_block_cs_ccd_dflop_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_2 || ORIG_REF_NAME==top_block_clk_wiz_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_1/top_block_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_1 || ORIG_REF_NAME==top_block_xlslice_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_2/top_block_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_2 || ORIG_REF_NAME==top_block_xlslice_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_3/top_block_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_3 || ORIG_REF_NAME==top_block_xlslice_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_1_0/top_block_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_1_0 || ORIG_REF_NAME==top_block_xlslice_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_cs_clk_sel_0_0/top_block_cs_clk_sel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_cs_clk_sel_0_0 || ORIG_REF_NAME==top_block_cs_clk_sel_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_m00_data_fifo_0 || ORIG_REF_NAME==top_block_m00_data_fifo_0} -quiet] -quiet

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_vio_0_0/top_block_vio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_vio_0_0 || ORIG_REF_NAME==top_block_vio_0_0} -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_0/top_block_rst_clk_wiz_0_125M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_0/top_block_rst_clk_wiz_0_125M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_0_0/synth/top_block_xpm_cdc_gen_0_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_0/top_block_rst_clk_wiz_1_320M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_0/top_block_rst_clk_wiz_1_320M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_1/top_block_rst_clk_wiz_1_320M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_1 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_1/top_block_rst_clk_wiz_1_320M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_1 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_0_2/synth/top_block_xpm_cdc_gen_0_2_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_0_3/synth/top_block_xpm_cdc_gen_0_3_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_1/top_block_rst_clk_wiz_0_125M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_1 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_1/top_block_rst_clk_wiz_0_125M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_1 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_300M1_0/top_block_rst_clk_wiz_0_300M1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_300M1_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_300M1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_300M1_0/top_block_rst_clk_wiz_0_300M1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_300M1_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_300M1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_2_0/synth/top_block_xpm_cdc_gen_2_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_blk_mem_gen_0_0/top_block_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_axi_iic_0_0/top_block_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_axi_iic_0_0 || ORIG_REF_NAME==top_block_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_axi_iic_0_0/top_block_axi_iic_0_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_0_2/top_block_fifo_generator_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_0_0 || ORIG_REF_NAME==top_block_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_0_2/top_block_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_0_0 || ORIG_REF_NAME==top_block_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_1/top_block_fifo_generator_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_0_1 || ORIG_REF_NAME==top_block_fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_1/top_block_fifo_generator_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_0_1 || ORIG_REF_NAME==top_block_fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_1_0_2/top_block_fifo_generator_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_1_0 || ORIG_REF_NAME==top_block_fifo_generator_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_1_0_2/top_block_fifo_generator_1_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_1_0 || ORIG_REF_NAME==top_block_fifo_generator_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_2_0_2/top_block_fifo_generator_2_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_2_0 || ORIG_REF_NAME==top_block_fifo_generator_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_2_0_2/top_block_fifo_generator_2_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_fifo_generator_2_0 || ORIG_REF_NAME==top_block_fifo_generator_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_1_0 || ORIG_REF_NAME==top_block_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_1_0 || ORIG_REF_NAME==top_block_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_0 || ORIG_REF_NAME==top_block_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_0 || ORIG_REF_NAME==top_block_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_2 || ORIG_REF_NAME==top_block_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_2 || ORIG_REF_NAME==top_block_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_block_m00_data_fifo_0 || ORIG_REF_NAME==top_block_m00_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0_ooc.xdc

# XDC: /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/top_block_ooc.xdc
