# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.runs/synth_1/top_block_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param chipscope.maxJobs 8
set_param power.BramSDPPropagationFix 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {Timing 38-316}  -suppress 
set_msg_config  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '10.000' specified during out-of-context synthesis of instance 'u_FMP_Inst/u_RD_FIFO' at clock pin 'rd_clk' is different from the actual clock period '6.667', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -id {Timing 38-316}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design toplevel has port PHY_HPD driven by constant 0}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcau15p-sbvb484-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.cache/wt [current_project]
set_property parent.project_path /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/delay_adjust_init_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/init_i2c_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/INIT_I2C_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/SAMPA_TRG_EN_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/data_receiver_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/data_sender_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/SAMPA_PON_2_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/I2C_Controller_1_0
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/ip_repo/start_i2c_write_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/new/LED_REG_READ_SEPARATE_v1_0_M00_AXI.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/new/LED_REG_READ_SEPARATE_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/new/u_led_inst.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/I2C_Controller_v1_0_M00_AXI.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/I2C_Controller_v1_0_M01_AXI.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/I2C_Controller_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/ip_repo/SAMPA_TRG_EN_1_0/hdl/SAMPA_TRG_EN_v1_0_M00_AXI.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/ip_repo/init_i2c_1_0/hdl/init_i2c_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/cs_appunit_fifo_out.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/ip_repo/data_sender_1_0/hdl/data_sender_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/cs_fifo_slicer.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/cs_appunit_merge.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/trigger_manager.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/sources_1/new/cs_event_builder.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/sources_1/imports/new/cs_data_processor.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/sources_1/imports/new/cs_das_rx.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/threshold_comparator.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/mii_init.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/RESET_INST.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_clocking.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_reset_sync_ex.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_resets.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_support.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_sync_block_ex.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_tx_elastic_buffer.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/gig_ethernet_pcs_pma_0_example_design.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/reg_switch.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/new/native_to_axi_lite_v1_0_M00_AXI.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/new/native_to_axi_lite_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/ip_repo/data_receiver_1_0/hdl/data_receiver_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/ip_repo/delay_adjust_init_1_0/hdl/delay_adjust_init_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/idelay_controller_v2.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/idelay_impl_v2.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/idelay_impl_v2_normal.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/idelay_top_v2.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/ip_repo/SAMPA_TRG_EN_1_0/hdl/SAMPA_TRG_EN_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/OBUFDS_TRG.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/TRG_MODULE.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/OBUFDS_CLKSOIN.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/bits_to_n_samples.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/OBUFDS_CONST.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/SAMPA_PON_v1_0_M00_AXI.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/SAMPA_PON_v1_0.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/GPIO_rx.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/cs_ccd_dflop.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/cs_clk_sel.v
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/hdl/top_block_wrapper.v
}
read_vhdl -library xil_defaultlib {
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/new/iobuf_vhdl.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_records.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_util_pkg.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/text_config_data.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/common/efb_xilinx_dna_port.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_data_array_inject.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_reg_counters.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/common/efb_sim_events.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_ram_block_data.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/common/efb_lmd_format_events.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/common/efb_lmd_buffer_events.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_crc32.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_in_state.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_dyn_control.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_ntp_query_control.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_mon_pkt_control.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_packet_gen.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_out_state.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_out_pipeline.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_regaccess.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_ram_block_a11d16.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_local_reg.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_tcp_state.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_tcp_control.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_tcp_prepare.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_tcp_buffer.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_test_datagen.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_ram_block_stat.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_regacc_aux_stat.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_mdio.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fakernet_module.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/efb_common_top.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_rx_speed_sense.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_octet_to_word.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/vhdl/fnet_async_fifo.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_word_in_fifo.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_gmii_mii_rx.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_word_out_fifo.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_word_to_octet.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/ddr/efnet_xilinx_oddr_by_oddr2.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/lib/fakernet/extra_vhdl/efnet_gmii_mii_tx.vhd
  /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/imports/nagafusa/work/spadi/Fakernet/SAMIDARE/imports/fakernet_top.vhd
}
read_ip -quiet /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/gig_ethernet_pcs_pma_0.xci
set_property used_in_synthesis false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/example_design/gig_ethernet_pcs_pma_0_example_design.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/example_design/gig_ethernet_pcs_pma_0_example_design.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/synth/gig_ethernet_pcs_pma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_2/synth/gig_ethernet_pcs_pma_0_ooc.xdc]

read_ip -quiet /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_gt/gig_ethernet_pcs_pma_0_gt.xci
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt.xdc]

add_files /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/sources_1/bd/top_block/top_block.bd
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_vio_0_0/top_block_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_0/top_block_rst_clk_wiz_0_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_0/top_block_rst_clk_wiz_0_125M_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_0_0/synth/top_block_xpm_cdc_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_0/top_block_rst_clk_wiz_1_320M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_0/top_block_rst_clk_wiz_1_320M_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_1/top_block_rst_clk_wiz_1_320M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_1_320M_1/top_block_rst_clk_wiz_1_320M_1.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_0_2/synth/top_block_xpm_cdc_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_0_3/synth/top_block_xpm_cdc_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_1/top_block_rst_clk_wiz_0_125M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_125M_1/top_block_rst_clk_wiz_0_125M_1.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_300M1_0/top_block_rst_clk_wiz_0_300M1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_rst_clk_wiz_0_300M1_0/top_block_rst_clk_wiz_0_300M1_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_xpm_cdc_gen_2_0/synth/top_block_xpm_cdc_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_blk_mem_gen_0_0/top_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_axi_iic_0_0/top_block_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_axi_iic_0_0/top_block_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_0_2/top_block_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_0_2/top_block_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_1/top_block_fifo_generator_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_0_1/top_block_fifo_generator_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_1_0_2/top_block_fifo_generator_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_1_0_2/top_block_fifo_generator_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_2_0_2/top_block_fifo_generator_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_fifo_generator_2_0_2/top_block_fifo_generator_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_clk_wiz_0_2/top_block_clk_wiz_0_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.gen/sources_1/bd/top_block/top_block_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/GTH.xdc
set_property used_in_implementation false [get_files /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/GTH.xdc]

read_xdc /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/main_io.xdc
set_property used_in_implementation false [get_files /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/main_io.xdc]

read_xdc /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/samidare_io.xdc
set_property used_in_implementation false [get_files /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/samidare_io.xdc]

read_xdc /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/Pblock.xdc
set_property used_in_implementation false [get_files /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/Pblock.xdc]

read_xdc /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/Timing.xdc
set_property used_in_implementation false [get_files /home/claudio/Developer/Vivado/SAMIDARE_DAQ/SAMIDARE/samidare.srcs/constrs_1/new/Timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_block_wrapper -part xcau15p-sbvb484-1-i -gated_clock_conversion auto
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_block_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_block_wrapper_utilization_synth.rpt -pb top_block_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
